jdk: openjdk11
language: java
before_script:
  - if [ -n "$TRAVIS_TAG" ]; then
      export VERSIONING_GIT_TAG=$TRAVIS_TAG;
    elif [ -n "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      export VERSIONING_GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH;
    else
      export VERSIONING_GIT_BRANCH=$TRAVIS_BRANCH;
    fi
script:
- "./mvnw clean deploy -Pdeploy --batch-mode --errors --fail-at-end --show-version
  --settings deployment/settings.xml -Dgpg.keyname=F0FE0BBE14902B34"
before_install:
- openssl aes-256-cbc -K $encrypted_464f3278645d_key -iv $encrypted_464f3278645d_iv
  -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
- echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
- gpg2 --batch --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --secret-keyring=$TRAVIS_BUILD_DIR/secring.gpg
  --no-default-keyring --import deployment/signingkey.asc
env:
  global:
  - secure: WzQ1jGx35/EJgZ5kiJcpTbR28tCX/S1M7SQH2kq1EDXWscHUUhflHm+zGyPQPfmyT9DUrb9aP62ndEFEyTzavafcYcp6P086bAGl+5o0MQgbFkV96Ja9Qq2dw4FGIbvg4QJFgoRyjSlV1VJhNsfVmjTvHXpeJWJquq+IEEqOXktCvxlIrY0gT24dYI2ePu3yGBm6wimiMOWu+5X6SA1yHWbNel89CGXeO7aBFfBN5WCSfh90q7NOXC0n/usF7P8CrA1Oq08pMMUARxt9RybWfDPd6GnWhrOxEXH9lK1lDqLLXXs1i+hTHuX2rxYISWFfWGwmPUbMJIGwN8ySk2xjAW5Ec2Pv9gJpMbYnHoHv7VP7isySO1vZ+Mn3l9xbmINMPc3+2R/TjHXB/CFv2ILVhSq2W5DZXFiL2SKeQROw/8+NVmuVs2VEgBw/otmgJtv24N2OJEHu4cyHIqbp0Gb/bn6po8Kv9WTGKIdMhkTWHTZYLV47jyjaIOyGaZJ9L5q+ZZgn4ZtbyvhwG5UJ1vAeVktrgpQhGQEoby9oDbvb7AyKswXwpPnAhxV6l6K2V+Ak28hVhoJ2mQhhuGCttMtA7RVOBucG0iWxzUUWUsxJ1TuUjdBo0VGflk/DjlH+hlvQzvNCjA/UmkHjkVhUBK7fF58VbmDdgbeAnunNhsSHS7o=
  - secure: Rg42s+Q/nAssUt1AUF2Mfzlmzmp+TMAsS1rYscbOb+Rx9MzlnvFtGnaNuZ7Uv0quTtzP9vseBIttkl8Bd6/iNS9wa/JeWw/O1eLc2cEFFe5HKs9E8gXFQ5eYbX4NqrPMFNEe+gt/jni8k4LSUC/Jxf8Nf374b0d8U8oYe3MoFJ6tC54cmtJW5c0E61x7uBc5gUZdxbrDDmXUBkAEB4k1PCUSKoWswuDZjbx++ipAZ3j0+o3C/qVTpLgvUfkKgtpbMx+xUqNuJmikPGKERcIAYHn9js0klaA8JMgK4BHC6cyC0h43EgbpY1SAEcfLtVD4aQSWILbGAqHQCA9JkNQBPumUjKSq8ZfC9/QZNYIHqIJTZHiVWrgzrJzn9BIEfMu27EdvBxa7x7RB0J8ngjDYJQFMeq9n2oAH33d/AiMau19TO6zIx0Yc4hGfUNwp8R421SXgAyiaXf60Ale/KwBP3slu/dWrtdkzPEcND46kLHSP3eVosjoznOIBsriXN78K+kaSz932plF5eMMjbpwsEuxtm2lsuUR99ngLMq7CPFikEa6eIznfvCP0jvl52cTlSwW+HiXjI1pHf3aYkj9VFbxTxX6ytWqjDyUlSLgLEvqjkAl1DKcZ6HBIEXjQfJDrOb8TjzFWWgh6JJH1lMxl6qfbZt9EsbhOxtilx+5W7Ys=
  - secure: lwJn9Wk9wTMaDFOrQbgiY3N1hBGPzdGpEhHTFEsdVzSqV2svaQl0omC13aDeFrrBPvAqdPWvdTKzz6lrkH/S0PnK7prvJFsQAPrpDL7p+YoLyg/T5T78NfjAaFGrxK0d8TssCowVl+sNpWiarsj3KZT9LRIC+BXKU+HeuTeu87FK5DCjozDyTAXTFRpNYKcqCP+cJl8xpkMajjjZbLW92AZVUP0Dqhr65YNt0mORjgdsQEOusHqTpKirai8HFDNKuKjunkhI4JYvVuV4xPwicQpbhPDaQh4iA0K/UBPZbBL3bBNu/jQBBjyfe/GVYpr1Gzy1Qm/7f4YgzD7EIADcU/x60uhyUEU6sA3rwcrUvdSsOqj4OHXwZb83LtIPBGq/ZWsfeBiZYasrSikxmHomHBxDRzJnvgxH+53MmFruec56oI4Eh00jO7aU+40p8As1OzY07eBcgSPDYmopebm8QPPGjxaFPuJxBUrqqLcuRnaSPf6PHorZSNpqJztfQ6OMlR9E0Gqz3wVrOJm2ZONzEEHF7LwnchVaBsmJUStX8GguYOxn0jQv5tzWhSMUfd52z4J/W/LJMbZnOvUYxPjavroWBswd95pnNwjGKHoVCUWu+cGPWUFfw227fV2pABVPAaGBFRDnqj+ubWyCIwPBbSAijA9xhfebOfgdBXyAdiY=
